services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"  # Puerto del proxy expuesto en el host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./welcome.html:/usr/share/nginx/html/index.html
    depends_on:
      - app1
      - app2

  app1:
    image: nginx:latest
    ports:
      - "8000:80"  # Exponer el puerto 8000 al host y mapearlo al puerto 80 dentro del contenedor
    volumes:
      - ./Sintaxify/index.html:/usr/share/nginx/html/index.html

  app2:
    image: nginx:latest
    ports:
      - "8001:80"  # Exponer el puerto 8001 al host y mapearlo al puerto 80 dentro del contenedor
    volumes:
      - ./AuthenticationServerFrontend/index.html:/usr/share/nginx/html/index.html
